(function (app) {
  'use strict';

  // Start by defining the main module and adding the module dependencies
  angular
    .module(app.applicationModuleName, app.applicationModuleVendorDependencies);

  // Setting HTML5 Location Mode
  angular
    .module(app.applicationModuleName)
    .config(bootstrapConfig);

  bootstrapConfig.$inject = ['$compileProvider', '$locationProvider', '$httpProvider', '$logProvider', '$uiViewScrollProvider', '$translateProvider'];

  function bootstrapConfig($compileProvider, $locationProvider, $httpProvider, $logProvider, $uiViewScrollProvider, $translateProvider) {
    $locationProvider.html5Mode({
      enabled: true,
      requireBase: false
    }).hashPrefix('!');

    $httpProvider.interceptors.push('authInterceptor');

    // Initialize 'get' if not there
    if (!$httpProvider.defaults.headers.get) {
        $httpProvider.defaults.headers.get = {};
    }

    // Disable IE ajax request caching
    $httpProvider.defaults.headers.get['If-Modified-Since'] = 'Mon, 26 Jul 1997 05:00:00 GMT';
    $httpProvider.defaults.headers.get['Cache-Control'] = 'no-cache';
    $httpProvider.defaults.headers.get['Pragma'] = 'no-cache';

    // Disable debug data for production environment
    // @link https://docs.angularjs.org/guide/production
    $compileProvider.debugInfoEnabled(app.applicationEnvironment !== 'production');
    $logProvider.debugEnabled(app.applicationEnvironment !== 'production');

    $uiViewScrollProvider.useAnchorScroll();

    $translateProvider.translations('en', {
      TEAMS: 'Teams',
      PROJECTS: 'Projects',
      OPPORTUNITIES: 'Opportunities',
      SIGNUP: 'Sign Up',
      SIGNIN: 'Sign In',
      HOME: 'Home',
      BETA: 'Beta',
      BETA_DESC: 'The term “beta” in software development refers to a development phase within its lifecycle that provides opportunities to conduct proofing and testing often with users from outside of the project team (general public).  This allows the project team to adjust the product according to new test data. The distribution of a beta release can be as limiting or vast as project resources allow. The goal of a beta release is to garner feedback on, but not exclusively to, the design, process, and demand by collecting user experience comments and statistics. A beta is ephemeral in nature, and moves into official production status once the proofing and testing is successful.',
      CHANGE_LANGUAGE: 'Français',
      TITLE: 'Government of Canada Developers Exchange',
      ABOUT_TITLE: 'About GC DevEx Beta',
      ABOUT_P1: 'The Government of Canada Developers Exchange (GC Dev Ex Beta) is a micro-procurement platform where teams within the Government of Canada can post <a href="/en/opportunities">opportunities</a> to developers who are eligible to work in Canada. The dollar value of these contracts cannot exceed $10,000 CAD, including GST. This is one of several initiatives underway to make it easier for government and developers to work together.',
      ABOUT_P2: '<a href="/en/authentication/government">Register now</a> to be notified of future opportunities!',
      DEPTS_TITLE: 'Participating government departments',
      DEPTS_P1: 'GC Dev Ex Beta was started by Privy Council Office (PCO) and Treasury Board of Canada Secretariat (TBS), in collaboration with Public Services and Procurement Canada (PSPC). These departments are responsible for managing the beta site and evaluating the initiative.',
      DEPTS_P2: 'Other federal departments who wish to use the GC Dev Ex Beta can contact <a href="mailto:consultation@pco-bcp.gc.ca">consultation@pco-bcp.gc.ca</a>. Once evaluated, the initiative may be expanded.',
      CODE_TITLE: 'Re-use this code',
      CODE_P1: 'The code for the GC Dev Ex Beta platform was first developed by the Government of British Columbia for its <a href="https://bcdevexchange.org/">British Columbia Developers\' Exchange</a>. It was then modified to meet Treasury Board of Canada Secretariat (TBS) Web Standards and the <em>Official Languages Act</em>.',
      CODE_P2: 'Other governments can re-use this modified code. With the exception of the federal identifier (AKA Canada logo), all parts of the platform are licensed for re-use through the <a href="http://www.apache.org/licenses/">Apache License</a>.',
      CODE_P3: 'Whether you are part of a provincial, municipal, or national government elsewhere, you can fork the code on GitHub and set-up your own micro-procurement platform to work with developers in your community.',
      IMG_CAP1: '',
      IMG_CAP2: '',
      IMG_CAP3: '',
      VID_TITLE: 'Government collaboration at CodeFest',
      VID_P1: 'Highlights from the 2<sup>nd</sup> CodeFest held in August 2013.',
      LINKS_TITLE1: 'Work With Us',
      LINKS_A1: '<a href="https://github.com/canada-ca/welcome">Canada on GitHub</a>',
      LINKS_A2: '<a href="https://www.canada.ca/en/treasury-board-secretariat/topics/government-communications.html">Web Standards Policies</a>',
      LINKS_TITLE2: 'Open Source in Canada\'s Governments',
      LINKS_B1: '<a href="http://wet-boew.github.io/wet-boew/index.html">Web Experience Toolkit</a>',
      LINKS_B2: '<a href="https://github.com/gctools-outilsgc">GC 2.0 Tools on GitHub</a>',
      LINKS_B3: '<a href="https://bcdevexchange.org">B.C. Developers Exchange</a>',
      LINKS_B4: '<a href="https://government.github.com/community#canada">Canadian Government Accounts on GitHub</a>',
      SUBFOOTER_TITLE: 'About government',
      SUBFOOTER_LINK1: '<a href="https://www.canada.ca/en/contact.html">Contact us</a>',
      SUBFOOTER_LINK2: '<a href="https://www.canada.ca/en/government/dept.html">Departments and agencies</a>',
      SUBFOOTER_LINK3: '<a href="https://www.canada.ca/en/government/publicservice.html">Public service and military</a>',
      SUBFOOTER_LINK4: '<a href="https://www.canada.ca/en/news.html">News</a>',
      SUBFOOTER_LINK5: '<a href="https://www.canada.ca/en/government/system/laws.html">Treaties, laws and regulations</a>',
      SUBFOOTER_LINK6: '<a href="https://www.canada.ca/en/transparency/reporting.html">Government-wide reporting</a>',
      SUBFOOTER_LINK7: '<a href="http://pm.gc.ca/eng">Prime Minister</a>',
      SUBFOOTER_LINK8: '<a href="https://www.canada.ca/en/government/system.html">How government works</a>',
      SUBFOOTER_LINK9: '<a href="http://open.canada.ca/en/">Open government</a>',
      FOOTER_TITLE: 'About this site',
      FOOTER_LINK1: '<a href="https://www.canada.ca/en/social.html">Social media</a>',
      FOOTER_LINK2: '<a href="https://www.canada.ca/en/mobile.html">Mobile applications</a>',
      FOOTER_LINK3: '<a href="https://www1.canada.ca/en/newsite.html">About Canada.ca</a>',
      FOOTER_LINK4: '<a href="https://www.canada.ca/en/transparency/terms.html">Terms and conditions</a>',
      FOOTER_LINK5: '<a href="https://www.canada.ca/en/transparency/privacy.html">Privacy</a>',
      FOOTER_TOP: 'Top of Page <span class="glyphicon glyphicon-chevron-up"></span>',
      FOOTER_FIP: 'Symbol of the Government of Canada',
      ACTIONS: 'Actions',
      TEAMS_TITLE: 'Teams List',
      TEAMS_P1: 'The following table contains a list of all programs participating in GC DevEx beta. Filter the list by typing the name of a team or organization or sort a column using the arrows.',
      TEAMS_P2: 'This is not a full list of all GC programs. A full list of all GC services or information is available on <a href="https://www.canada.ca/en/services.html">canada.ca</a>.',
      TEAMS_TH1: 'Team Title',
      TEAMS_TH2: 'Description',
      TEAMS_TH3: 'Department',
      TEAMS_NONE: 'No open teams right now. Check back soon!',
      PROJ_TITLE: 'Projects List',
      PROJ_TH1: 'Project Title',
      PROJ_TH2: 'Description',
      PROJ_TH3: 'Team',
      PROJ_TH4: 'Tags',
      PROJ_NONE: 'No open projects right now. Check back soon!',
      OPP_TITLE: 'Opportunities List',
      OPP_TH1: 'Opportunity Title',
      OPP_TH2: 'Description',
      OPP_TH3: 'Project',
      OPP_TH4: 'Fixed Price',
      OPP_TH5: 'Closing Date',
      OPP_TH6: 'Tags',
      OPP_NONE: 'No open opportunities right now. Check back soon!',
      OPP_CTA: 'To get notified when new opportunities are posted, or post an opportunity yourself',
      OPP_FOR: 'Opportunities for ',
      OPP_GET_NOTIFIED: 'Want to get notified<span class="hidden-sm hidden-xs"> when new opportunities are posted</span>?',
      SIGNUP_P1: 'Join a community of developers, entrepreneurs, and public service innovators who are making public services better.',
      SIGNUP_GITHUB: 'Sign in with your GitHub account',
      SIGNUP_P2: 'Don\'t have one yet? It only takes a minute.',
      SIGNUP_PUBLIC_SECTOR: '<i class="fa fa-university"></i> &nbsp; Public Sector Employees',
      SIGNUP_P3: 'Raise your profile with developers and build a community around your open source project. <br>Hire talent fast.',
      SIGNUP_DEVELOPERS: 'Developers',
      SIGNUP_P4: 'Get notified about new opportunities and events in your area.',
      SIGNIN_HEADER: 'Or with your account',
      SIGNIN_EMAIL: 'Username or Email',
      SIGNIN_EMAIL_REQUIRED: 'Username or Email is required',
      SIGNIN_PASSWORD: 'Password',
      SIGNIN_PASSWORD_REQUIRED: 'Password is required',
      SIGNIN_OR: 'or',
      SIGNIN_FORGOT_PASSWORD: 'Forgot your password?',
      EMAIL: 'Email',
      MEMBER_SINCE: 'Member Since:',
      OPEN: 'OPEN',
      CLOSED: 'CLOSED',
      EDIT_PROFILE_SUCCESS: 'Edit profile successful',
      EDIT_PROFILE_SUCCESS_TEXT: 'You have requested government user access, the request is now posted for review. You will receive the government access and be able to access gov user functionality as soon as the admin verifies you as government user.',
      EDIT_PROFILE_OPPORTUNITIES: 'We will send you notifications of new Code With Us Opportunities.',
      EDIT_PROFILE_EVENTS: 'We will notify you of upcoming events.',
      EDIT_PROFILE_BLOG: 'We will notify you of new blog posts.',
      EDIT_PROFILE_FAILURE: 'Edit profile failed!',
      404: 'Page Not Found!',
      403: 'Forbidden!',
      400: 'Bad Request',
      IN_PERSON_NO: 'In-person work NOT required',
      IN_PERSON_YES: 'In-person work required',
      IN_PERSON_SOME: 'Some in-person work required',
      TEAM_TEAM: 'Team',
      TEAM_NEW: 'New Team',
      TEAM_MEMBERS: 'Team Members',
      TEAM_PROJECTS: 'Projects',
      TEAM_OPPORTUNITIES: 'Team Opportunities',
      PROJECT_NEW: 'New Project',
      PROJECT_GITHUB_REPO: 'View Code Repository on GitHub',
      PROJECT_MEMBERS: 'Project Members',
      PROJECT_OPPORTUNITIES: 'Project Opportunities',
      OPP_NEW: 'Post an Opportunity',
      OPP_CLOSING: 'Closing in:',
      OPP_UPDATES: 'Want <span class="hidden-sm hidden-xs">to get </span>updates<span class="hidden-sm hidden-xs"> about this opportunity</span>?',
      OPP_FIXED_PRICE: 'This is a <strong>fixed-price</strong> opportunity governed by the <a href="https://github.com/BCDevExchange/devex/raw/master/Code-with-Us%20Terms_BC%20Developers%20Exchange.pdf">terms</a> of our lightweight procurement model, <i><a href="/codewithus">Code With Us</a></i>.',
      OPP_BACKGROUND: 'Background',
      OPP_ACC_CRIT: 'Acceptance Criteria',
      OPP_PAID: 'To be paid the fixed price for this opportunity, you need to meet all of the following criteria:',
      OPP_PROPOSAL_EVAL: 'Proposal Evaluation Criteria',
      OPP_SCORED: 'Your proposal will be scored by this criteria:',
      OPP_HOW_TO_APPLY: 'How to Apply',
      OPP_SUBMIT_BEFORE: 'Submit your proposal before',
      OPP_INSTRUCTIONS: 'With your proposal, you must upload a copy of the <a href="https://github.com/BCDevExchange/devex/raw/master/Code-with-Us%20Terms_BC%20Developers%20Exchange.pdf">Code With Us terms,</a> to indicate your acceptance of the terms.',
      OPP_PLAN: 'We plan to assign this opportunity by',
      OPP_PLAN2: 'with work to start on',
      OPP_GITHUB_LINK: 'Visit the GitHub issue for this opportunity and post a comment.',
      OPP_POSTED_BY: 'Posted by:',
      OPP_TEAM: 'Team:',
      OPP_PROJECT: 'Project:',
      OPP_CODE: 'Code:',
      OPP_GITHUB_ISSUE: 'View Issue on GitHub',
      OPP_CREATED_ON: 'Created on',
      OPP_BY: 'by',
      OPP_UPDATED_ON: 'Last updated on',
      PROFILE_SETTINGS: 'Settings',
      PROFILE_PRIVACY: 'Privacy & Notifications',
      FORM_REQUIRED: '(required)',
      Empty_Department: 'Please make a selection',
      Aboriginal_Business_Canada: 'Aboriginal Business Canada',
      Administrative_Tribunals_Support_Service_of_Canada: 'Administrative Tribunals Support Service of Canada',
      Agriculture_and_Agri_Food_Canada: 'Agriculture and Agri-Food Canada',
      Atlantic_Canada_Opportunities_Agency: 'Atlantic Canada Opportunities Agency',
      Atlantic_Pilotage_Authority_Canada: 'Atlantic Pilotage Authority Canada',
      Atomic_Energy_of_Canada_Limited: 'Atomic Energy of Canada Limited',
      Auditor_General_of_Canada: 'Auditor General of Canada (Office of the)',
      Bank_of_Canada: 'Bank of Canada',
      Blue_Water_Bridge_Canada: 'Blue Water Bridge Canada',
      Business_Development_Bank_of_Canada: 'Business Development Bank of Canada',
      CORCAN: 'CORCAN',
      Canada_Agricultural_Review_Tribunal: 'Canada Agricultural Review Tribunal',
      Canada_Agriculture_and_Food_Museum: 'Canada Agriculture and Food Museum',
      Canada_Aviation_and_Space_Museum: 'Canada Aviation and Space Museum',
      Canada_Border_Services_Agency: 'Canada Border Services Agency',
      Canada_Centre_for_Inland_Waters: 'Canada Centre for Inland Waters',
      Canada_Council_for_the_Arts: 'Canada Council for the Arts',
      Canada_Deposit_Insurance_Corporation: 'Canada Deposit Insurance Corporation',
      Canada_Development_Investment_Corporation: 'Canada Development Investment Corporation',
      Canada_Economic_Development_for_Quebec_Regions: 'Canada Economic Development for Quebec Regions',
      Canada_Employment_Insurance_Commission: 'Canada Employment Insurance Commission',
      Canada_Firearms_Centre: 'Canada Firearms Centre',
      Canada_Gazette: 'Canada Gazette',
      Canada_Industrial_Relations_Board: 'Canada Industrial Relations Board',
      Canada_Lands_Company_Limited: 'Canada Lands Company',
      Canada_Mortgage_and_Housing_Corporation: 'Canada Mortgage and Housing Corporation',
      Canada_Pension_Plan_Investment_Board: 'Canada Pension Plan Investment Board',
      Canada_Post: 'Canada Post',
      Canada_Research_Chairs: 'Canada Research Chairs',
      Canada_Revenue_Agency: 'Canada Revenue Agency',
      Canada_School_of_Public_Service: 'Canada School of Public Service',
      Canada_Science_and_Technology_Museum_Corporation: 'Canada Science and Technology Museum Corporation',
      Canadian_Air_Transport_Security_Authority: 'Canadian Air Transport Security Authority',
      Canadian_Army: 'Canadian Army',
      Canadian_Cadet_Organizations: 'Canadian Cadet Organizations',
      Canadian_Centre_for_Occupational_Health_and_Safety: 'Canadian Centre for Occupational Health and Safety',
      Canadian_Coast_Guard: 'Canadian Coast Guard',
      Canadian_Commercial_Corporation: 'Canadian Commercial Corporation',
      Canadian_Conservation_Institute: 'Canadian Conservation Institute',
      Canadian_Cultural_Property_Export_Review_Board: 'Canadian Cultural Property Export Review Board',
      Canadian_Dairy_Commission: 'Canadian Dairy Commission',
      Canadian_Environmental_Assessment_Agency: 'Canadian Environmental Assessment Agency',
      Canadian_Food_Inspection_Agency: 'Canadian Food Inspection Agency',
      Canadian_Forces_Housing_Agency: 'Canadian Forces Housing Agency',
      Canadian_General_Standards_Board: 'Canadian General Standards Board',
      Canadian_Grain_Commission: 'Canadian Grain Commission',
      Canadian_Heritage: 'Canadian Heritage',
      Canadian_Heritage_Information_Network: 'Canadian Heritage Information Network',
      Canadian_Human_Rights_Commission: 'Canadian Human Rights Commission',
      Canadian_Institutes_of_Health_Research: 'Canadian Institutes of Health Research',
      Canadian_Intellectual_Property_Office: 'Canadian Intellectual Property Office',
      Canadian_Intergovernmental_Conference_Secretariat: 'Canadian Intergovernmental Conference Secretariat',
      Canadian_International_Trade_Tribunal: 'Canadian International Trade Tribunal',
      Canadian_Judicial_Council: 'Canadian Judicial Council',
      Canadian_Museum_for_Human_Rights: 'Canadian Museum for Human Rights',
      Canadian_Museum_of_Contemporary_Photography: 'Canadian Museum of Contemporary Photography',
      Canadian_Museum_of_History: 'Canadian Museum of History',
      Canadian_Museum_of_Immigration_at_Pier_21: 'Canadian Museum of Immigration at Pier 21',
      Canadian_Museum_of_Nature: 'Canadian Museum of Nature',
      Canadian_Northern_Economic_Development_Agency: 'Canadian Northern Economic Development Agency',
      Canadian_Nuclear_Safety_Commission: 'Canadian Nuclear Safety Commission',
      Canadian_Pari_Mutuel_Agency: 'Canadian Pari-Mutuel Agency',
      Canadian_Police_College: 'Canadian Police College',
      Canadian_Race_Relations_Foundation: 'Canadian Race Relations Foundation',
      Canadian_Radio_Television_and_Telecommunications_Commission: 'Canadian Radio-Television and Telecommunications Commission',
      Canadian_Security_Intelligence_Service: 'Canadian Security Intelligence Service',
      Canadian_Space_Agency: 'Canadian Space Agency',
      Canadian_Tourism_Commission: 'Canadian Tourism Commission',
      Canadian_Trade_Commissioner_Service: 'Canadian Trade Commissioner Service',
      Canadian_Transportation_Agency: 'Canadian Transportation Agency',
      Canadian_War_Museum: 'Canadian War Museum',
      Chief_Electoral_Officer: 'Chief Electoral Officer (Office of the)',
      Civilian_Review_and_Complaints_Commission_for_the_RCMP: 'Civilian Review and Complaints Commission for the RCMP',
      Clerk_of_the_Privy_Council: 'Clerk of the Privy Council',
      Commissioner_for_Federal_Judicial_Affairs_Canada: 'Commissioner for Federal Judicial Affairs Canada (Office of the)',
      Commissioner_of_Lobbying_of_Canada: 'Commissioner of Lobbying of Canada (Office of the)',
      Commissioner_of_Official_Languages: 'Commissioner of Official Languages (Office of the)',
      Communications_Research_Centre_Canada: 'Communications Research Centre Canada',
      Communications_Security_Establishment_Canada: 'Communications Security Establishment Canada',
      Communications_Security_Establishment_Commissioner: 'Communications Security Establishment Commissioner (Office of the)',
      Competition_Bureau_Canada: 'Competition Bureau Canada',
      Competition_Tribunal: 'Competition Tribunal',
      Conflict_of_Interest_and_Ethics_Commissioner: 'Conflict of Interest and Ethics Commissioner (Office of the)',
      Copyright_Board_Canada: 'Copyright Board Canada',
      Correctional_Investigator_Canada: 'Correctional Investigator Canada',
      Correctional_Service_Canada: 'Correctional Service Canada',
      Courts_Administration_Service: 'Courts Administration Service',
      Currency_Museum: 'Currency Museum',
      Defence_Construction_Canada: 'Defence Construction Canada',
      Defence_Research_and_Development_Canada: 'Defence Research and Development Canada',
      Democratic_Institutions: 'Democratic Institutions',
      Destination_Canada: 'Destination Canada',
      Elections_Canada: 'Elections Canada',
      Employment_and_Social_Development_Canada: 'Employment and Social Development Canada',
      Environment_and_Climate_Change_Canada: 'Environment and Climate Change Canada',
      Environmental_Protection_Review_Canada: 'Environmental Protection Review Canada',
      Export_Development_Canada: 'Export Development Canada',
      Farm_Credit_Canada: 'Farm Credit Canada',
      Farm_Products_Council_of_Canada: 'Farm Products Council of Canada',
      Federal_Bridge_Corporation: 'Federal Bridge Corporation',
      Federal_Court_of_Appeal: 'Federal Court of Appeal',
      Federal_Court_of_Canada: 'Federal Court of Canada',
      Federal_Economic_Development_Agency_for_Southern_Ontario: 'Federal Economic Development Agency for Southern Ontario',
      Federal_Economic_Development_Initiative_for_Northern_Ontario: 'Federal Economic Development Initiative for Northern Ontario (FedNor)',
      Federal_Ombudsman_for_Victims_Of_Crime: 'Federal Ombudsman for Victims Of Crime (Office of the)',
      Finance_Canada: 'Finance Canada (Department of)',
      Financial_Consumer_Agency_of_Canada: 'Financial Consumer Agency of Canada',
      Financial_Transactions_and_Reports_Analysis_Centre_of_Canada: 'Financial Transactions and Reports Analysis Centre of Canada',
      Fisheries_and_Oceans_Canada: 'Fisheries and Oceans Canada',
      Freshwater_Fish_Marketing_Corporation: 'Freshwater Fish Marketing Corporation',
      Geographical_Names_Board_of_Canada: 'Geographical Names Board of Canada',
      Geomatics_Canada: 'Geomatics Canada',
      Global_Affairs_Canada: 'Global Affairs Canada',
      Governor_General_of_Canada: 'Governor General of Canada',
      Great_Lakes_Pilotage_Authority_Canada: 'Great Lakes Pilotage Authority Canada',
      Health_Canada: 'Health Canada',
      Historic_Sites_and_Monuments_Board_of_Canada: 'Historic Sites and Monuments Board of Canada',
      House_of_Commons: 'House of Commons',
      Human_Rights_Tribunal_of_Canada: 'Human Rights Tribunal of Canada',
      Immigration_and_Refugee_Board_of_Canada: 'Immigration and Refugee Board of Canada',
      Immigration_Refugees_and_Citizenship_Canada: 'Immigration, Refugees and Citizenship Canada',
      Indian_Oil_and_Gas_Canada: 'Indian Oil and Gas Canada',
      Indian_Residential_Schools_Truth_and_Reconciliation_Commission: 'Indian Residential Schools Truth and Reconciliation Commission',
      Indigenous_and_Northern_Affairs_Canada: 'Indigenous and Northern Affairs Canada',
      Industrial_Technologies_Office: 'Industrial Technologies Office',
      Information_Commissioner: 'Information Commissioner (Office of the)',
      Infrastructure_Canada: 'Infrastructure Canada',
      Innovation_Science_and_Economic_Development_Canada: 'Innovation, Science and Economic Development Canada',
      Intergovernmental_Affairs: 'Intergovernmental Affairs (Department of)',
      International_Development_Research_Centre: 'International Development Research Centre',
      Jacques_Cartier_and_Champlain_Bridges_Inc: 'Jacques Cartier and Champlain Bridges Inc.',
      Justice_Canada: 'Justice Canada (Department of)',
      Labour_Program: 'Labour Program',
      Laurentian_Pilotage_Authority_Canada: 'Laurentian Pilotage Authority Canada',
      Leader_of_the_Government_in_the_House_of_Commons: 'Leader of the Government in the House of Commons',
      Library_and_Archives_Canada: 'Library and Archives Canada',
      Marine_Atlantic: 'Marine Atlantic',
      Measurement_Canada: 'Measurement Canada',
      Military_Grievances_External_Review_Committee: 'Military Grievances External Review Committee',
      Military_Police_Complaints_Commission_of_Canada: 'Military Police Complaints Commission of Canada',
      National_Arts_Centre: 'National Arts Centre',
      National_Battlefields_Commission: 'National Battlefields Commission',
      National_Capital_Commission: 'National Capital Commission',
      National_Defence: 'National Defence',
      National_Defence_and_the_Canadian_Forces_Ombudsperson: 'National Defence and the Canadian Forces Ombudsperson (Office of the)',
      National_Energy_Board: 'National Energy Board',
      National_Film_Board: 'National Film Board',
      National_Gallery_of_Canada: 'National Gallery of Canada',
      National_Museum_of_Science_and_Technology: 'National Museum of Science and Technology',
      National_Research_Council_Canada: 'National Research Council Canada',
      National_Search_and_Rescue_Secretariat: 'National Search and Rescue Secretariat',
      National_Seniors_Council: 'National Seniors Council',
      Natural_Resources_Canada: 'Natural Resources Canada',
      Natural_Sciences_and_Engineering_Research_Canada: 'Natural Sciences and Engineering Research Canada',
      Northern_Pipeline_Agency_Canada: 'Northern Pipeline Agency Canada',
      Occupational_Health_and_Safety_Tribunal_Canada: 'Occupational Health and Safety Tribunal Canada',
      PPP_Canada: 'PPP Canada',
      Pacific_Pilotage_Authority_Canada: 'Pacific Pilotage Authority Canada',
      Parks_Canada: 'Parks Canada',
      Parliament_of_Canada: 'Parliament of Canada',
      Office_of_the_Parliamentary_Budget_Officer: 'Parliamentary Budget Officer (Office of the)',
      Parliamentary_Protective_Service: 'Parliamentary Protective Service',
      Parole_Board_of_Canada: 'Parole Board of Canada',
      Passport_Canada: 'Passport Canada',
      Patented_Medicine_Prices_Review_Board_Canada: 'Patented Medicine Prices Review Board Canada',
      Polar_Knowledge_Canada: 'Polar Knowledge Canada',
      Policy_Horizons_Canada: 'Policy Horizons Canada',
      Prime_Minister_of_Canada: 'Prime Minister of Canada',
      Privacy_Commissioner: 'Privacy Commissioner (Office of the)',
      Privy_Council_Office: 'Privy Council Office',
      Procurement_Ombudsman: 'Procurement Ombudsman (Office of the)',
      Public_Health_Agency_of_Canada: 'Public Health Agency of Canada',
      Public_Prosecution_Service_of_Canada: 'Public Prosecution Service of Canada',
      Public_Safety_Canada: 'Public Safety Canada',
      Public_Sector_Integrity_Commissioner_of_Canada: 'Public Sector Integrity Commissioner of Canada (Office of the)',
      Public_Sector_Pension_Investment_Board: 'Public Sector Pension Investment Board',
      Public_Servants_Disclosure_Protection_Tribunal_Canada: 'Public Servants Disclosure Protection Tribunal Canada',
      Public_Service_Commission_of_Canada: 'Public Service Commission of Canada',
      Public_Service_Labour_Relations_and_Employment_Board: 'Public Service Labour Relations and Employment Board',
      Public_Services_and_Procurement_Canada: 'Public Services and Procurement Canada',
      Receiver_General_for_Canada: 'Receiver General for Canada',
      Registry_of_the_Specific_Claims_Tribunal_of_Canada: 'Registry of the Specific Claims Tribunal of Canada',
      Ridley_Terminals_Inc: 'Ridley Terminals Inc.',
      Royal_Canadian_Air_Force: 'Royal Canadian Air Force',
      Royal_Canadian_Mint: 'Royal Canadian Mint',
      Royal_Canadian_Mounted_Police: 'Royal Canadian Mounted Police',
      Royal_Canadian_Mounted_Police_External_Review_Committee: 'Royal Canadian Mounted Police External Review Committee',
      Royal_Canadian_Navy: 'Royal Canadian Navy',
      Royal_Military_College_Saint_Jean: 'Royal Military College Saint-Jean',
      Royal_Military_College_of_Canada: 'Royal Military College of Canada',
      Secretary_to_the_Governor_General: 'Secretary to the Governor General (Office of the)',
      Security_Intelligence_Review_Committee: 'Security Intelligence Review Committee',
      Senate_of_Canada: 'Senate of Canada',
      Seniors: 'Seniors',
      Service_Canada: 'Service Canada',
      Shared_Services_Canada: 'Shared Services Canada',
      Ship_Source_Oil_Pollution_Fund: 'Ship-Source Oil Pollution Fund',
      Social_Sciences_and_Humanities_Research_Council_of_Canada: 'Social Sciences and Humanities Research Council of Canada',
      Social_Security_Tribunal_of_Canada: 'Social Security Tribunal of Canada',
      Sport_Canada: 'Sport Canada',
      Standards_Council_of_Canada: 'Standards Council of Canada',
      Statistics_Canada: 'Statistics Canada',
      Status_of_Women_Canada: 'Status of Women Canada',
      Superintendent_of_Bankruptcy_Canada: 'Superintendent of Bankruptcy Canada (Office of the)',
      Superintendent_of_Financial_Institutions_Canada: 'Superintendent of Financial Institutions Canada (Office of the)',
      Supreme_Court_of_Canada: 'Supreme Court of Canada',
      Tax_Court_of_Canada: 'Tax Court of Canada',
      Taxpayers_Ombudsman: 'Taxpayers\' Ombudsman (Office of the)',
      Telefilm_Canada: 'Telefilm Canada',
      Translation_Bureau: 'Translation Bureau',
      Transport_Canada: 'Transport Canada',
      Transportation_Appeal_Tribunal_of_Canada: 'Transportation Appeal Tribunal of Canada',
      Transportation_Safety_Board_of_Canada: 'Transportation Safety Board of Canada',
      Treasury_Board_of_Canada_Secretariat: 'Treasury Board of Canada Secretariat',
      VIA_Rail_Canada_Inc: 'VIA Rail Canada Inc.',
      Veterans_Affairs_Canada: 'Veterans Affairs Canada',
      Veterans_Review_and_Appeal_Board_Canada: 'Veterans Review and Appeal Board Canada',
      Veterans_Ombudsman: 'Veterans\' Ombudsman (Office of the)',
      Virtual_Museum_of_Canada: 'Virtual Museum of Canada',
      Western_Economic_Diversification_Canada: 'Western Economic Diversification Canada',
      500: '$500',
      1000: '$1,000',
      1500: '$1,500',
      2000: '$2,000',
      2500: '$2,500',
      3000: '$3,000',
      3500: '$3,500',
      4000: '$4,000',
      4500: '$4,500',
      5000: '$5,000',
      5500: '$5,500',
      6000: '$6,000',
      6500: '$6,500',
      7000: '$7,000',
      7500: '$7,500',
      8000: '$8,000',
      8500: '$8,500',
      9000: '$9,000',
      9500: '$9,500',
      10000: '$10,000'
    })
    .translations('fr', {
      TEAMS: 'Équipes',
      PROJECTS: 'Projets',
      OPPORTUNITIES: 'Possibilités',
      SIGNUP: 'S\'inscrire',
      SIGNIN: 'Se connecter',
      HOME: 'Accueil',
      BETA: 'Bêta',
      BETA_DESC: 'Dans le cadre du développement de logiciels, le terme « bêta » renvoie à une étape de son cycle de vie qui offre la possibilité de faire des examens et des essais, souvent auprès d\'utilisateurs de l\'extérieur de l\'équipe de projet (le grand public). L\'équipe de projet peut ainsi rajuster le projet en fonction des nouvelles données mises à l\'essai. La diffusion d\'une version bêta peut être aussi restreinte ou aussi vaste que le permettent les ressources du projet. La version bêta vise à obtenir de la rétroaction sur notamment la conception, le processus et la demande en recueillant des commentaires sur l\'expérience des utilisateurs ainsi que des statistiques. Une version bêta est de nature éphémère et arrive à l\'étape de production officielle une fois que les examens et les essais sont concluants.',
      CHANGE_LANGUAGE: 'English',
      TITLE: 'Le Carrefour des développeurs du gouvernement du Canada',
      ABOUT_TITLE: 'À propos de CarrefourProgGC bêta',
      ABOUT_P1: 'Le Carrefour des développeurs du gouvernement du Canada (CarrefourProgGC bêta) est une plateforme de micro-approvisionnement où des équipes du gouvernement du Canada peuvent afficher des <a href="/fr/opportunities">possibilités de travail contractuel</a> à l\'intention des développeurs qui ont le droit de travailler au Canada. La valeur des contrats ne doit pas dépasser 10 000 $ CA, TPS comprise. Le Carrefour fait partie de plusieurs initiatives en cours visant à aider le gouvernement et les développeurs à travailler ensemble.',
      ABOUT_P2: '<a href="/fr/authentication/government">Inscrivez-vous</a> maintenant pour être avisé des futures possibilités!',
      DEPTS_TITLE: 'Ministères participants',
      DEPTS_P1: 'Le CarrefourProgGC bêta a été lancé par le Bureau du Conseil privé (BCP) et le Secrétariat du Conseil du Trésor du Canada (SCT) en collaboration avec Services publics et Approvisionnement Canada (SPAC). Ces ministères sont responsables de la gestion du site bêta et de l\'évaluation de l\'initiative.',
      DEPTS_P2: 'Les autres ministères fédéraux qui souhaitent utiliser le CarrefourProgGC bêta peuvent communiquer avec <a href="mailto:consultation@pco-bcp.gc.ca">consultation@pco-bcp.gc.ca</a>. L\'initiative pourrait être étendue, une fois l\'évaluation nécessaire effectuée.',
      CODE_TITLE: 'Réutilisation du code',
      CODE_P1: 'Le code pour la plateforme CarrefourProgGC bêta a d\'abord été développé par le gouvernement de la Colombie-Britannique pour sa plateforme <a href="https://bcdevexchange.org/">British Columbia Developers\' Exchange</a>, puis modifié pour satisfaire aux normes Web du Secrétariat du Conseil du Trésor (SCT) et à la <em>Loi sur les langues officielles</em>.',
      CODE_P2: 'Les autres gouvernements peuvent réutiliser ce code modifié. En effet, il est possible de réutiliser tous les éléments de la plateforme, sauf l\'identificateur fédéral (c.‑à‑d. le logo du Canada), grâce à la <a href="http://www.apache.org/licenses/">licence Apache</a>.',
      CODE_P3: 'Que vous fassiez partie d\'un gouvernement provincial, d\'une administration municipale ou d\'un gouvernement national à l\'étranger, vous pouvez copier le code sur GitHub et établir votre propre plateforme de micro-approvisionnement afin de travailler avec les développeurs de votre communauté.',
      IMG_CAP1: '',
      IMG_CAP2: '',
      IMG_CAP3: '',
      VID_TITLE: 'Collaboration gouvernementale à CodeFest',
      VID_P1: 'Faits saillants de la 2<sup>ème</sup> CodeFest tenue en août 2013.',
      LINKS_TITLE1: 'Travailler avec nous',
      LINKS_A1: '<a href="https://github.com/canada-ca/welcome">Le Canada et GitHub</a>',
      LINKS_A2: '<a href="https://www.canada.ca/fr/secretariat-conseil-tresor/sujets/communications-gouvernementales.html">Politiques sur les normes Web</a>',
      LINKS_TITLE2: 'Source ouverte des gouvernements du Canada',
      LINKS_B1: '<a href="http://wet-boew.github.io/wet-boew/index.html">Boîte à outils de l\'expérience Web</a>',
      LINKS_B2: '<a href="https://github.com/gctools-outilsgc">Outils GC 2.0 sur GitHub</a>',
      LINKS_B3: '<a href="https://bcdevexchange.org">B.C. Developers Exchange</a>',
      LINKS_B4: '<a href="https://government.github.com/community#canada">Comptes du gouvernement canadien sur GitHub</a>',
      SUBFOOTER_TITLE: 'Au sujet du gouvernement',
      SUBFOOTER_LINK1: '<a href="https://www.canada.ca/fr/contact.html">Contactez-nous</a>',
      SUBFOOTER_LINK2: '<a href="https://www.canada.ca/fr/gouvernement/min.html">Ministères et organismes</a>',
      SUBFOOTER_LINK3: '<a href="https://www.canada.ca/fr/gouvernement/fonctionpublique.html">Fonction publique et force militaire</a>',
      SUBFOOTER_LINK4: '<a href="https://www.canada.ca/fr/nouvelles.html">Nouvelles</a>',
      SUBFOOTER_LINK5: '<a href="https://www.canada.ca/fr/gouvernement/systeme/lois.html">Traités, lois et règlements</a>',
      SUBFOOTER_LINK6: '<a href="https://www.canada.ca/fr/transparence/rapports.html">Rapports à l\'échelle du gouvernement</a>',
      SUBFOOTER_LINK7: '<a href="http://pm.gc.ca/fra">Premier ministre</a>',
      SUBFOOTER_LINK8: '<a href="https://www.canada.ca/fr/gouvernement/systeme.html">Comment le gouvernement fonctionne</a>',
      SUBFOOTER_LINK9: '<a href="http://ouvert.canada.ca/">Gouvernement ouvert</a>',
      FOOTER_TITLE: 'À propos du site',
      FOOTER_LINK1: '<a href="https://www.canada.ca/fr/sociaux.html">Médias sociaux</a>',
      FOOTER_LINK2: '<a href="https://www.canada.ca/fr/mobile.html">Applications mobiles</a>',
      FOOTER_LINK3: '<a href="https://www1.canada.ca/fr/nouveausite.html">À propos de Canada.ca</a>',
      FOOTER_LINK4: '<a href="https://www.canada.ca/fr/transparence/avis.html">Avis</a>',
      FOOTER_LINK5: '<a href="https://www.canada.ca/fr/transparence/confidentialite.html">Confidentialité</a>',
      FOOTER_TOP: 'Haut de la page <span class="glyphicon glyphicon-chevron-up"></span>',
      FOOTER_FIP: 'Symbole du gouvernement du Canada',
      ACTIONS: 'Actions',
      TEAMS_TITLE: 'Liste des équipes',
      TEAMS_P1: 'Le tableau suivant contient une liste de tous les programmes qui participent à CarrefourProgGC bêta. Filtrez la liste en inscrivant le nom d\'une équipe ou d\'une organisation ou triez une colonne au moyen des flèches.',
      TEAMS_P2: 'Ceci n\'est pas une liste complète de tous les programmes du gouvernement du Canada. Pour obtenir la liste complète de tous les services du gouvernement du Canada ou des renseignements à ce sujet, allez à canada.ca.',
      TEAMS_TH1: 'Nom de l\'équipe',
      TEAMS_TH2: 'Description',
      TEAMS_TH3: 'Ministère',
      TEAMS_NONE: 'Pas d\'équipes ouvertes en ce moment. Revenez bientôt!',
      PROJ_TITLE: 'Liste des projets',
      PROJ_TH1: 'Titre du projet',
      PROJ_TH2: 'Description',
      PROJ_TH3: 'Équipe',
      PROJ_TH4: 'Mots clés',
      PROJ_NONE: 'Pas de projets ouverts en ce moment. Revenez bientôt!',
      OPP_TITLE: 'Liste des possibilités',
      OPP_TH1: 'Titre de la possibilité',
      OPP_TH2: 'Description',
      OPP_TH3: 'Projet',
      OPP_TH4: 'Prix fixe',
      OPP_TH5: 'Date de clôture',
      OPP_TH6: 'Mots clés',
      OPP_NONE: 'Pas d\'opportunités ouvertes en ce moment. Revenez bientôt!',
      OPP_CTA: 'Pour être averti lorsque de nouvelles opportunités sont publiées ou pour poster une opportunité',
      OPP_FOR: 'Possibilités pour ',
      OPP_GET_NOTIFIED: 'Aimeriez-vous recevoir des mises à jour<span class="hidden-sm hidden-xs"> lorsque de nouvelles opportunités sont affichées</span>?',
      SIGNUP_P1: 'Rejoignez une communauté de développeurs, entrepreneurs et innovateurs de services publics qui améliorent les services publics.',
      SIGNUP_GITHUB: 'Connectez-vous avec votre compte GitHub',
      SIGNUP_P2: 'Vous n\'en avez pas encore? Ca prend juste une minute.',
      SIGNUP_PUBLIC_SECTOR: '<i class="fa fa-university"></i> &nbsp; Employés du secteur public',
      SIGNUP_P3: 'Augmentez votre profil avec les développeurs et créez une communauté autour de votre projet open source. <br>Embaucher des talents rapidement.',
      SIGNUP_DEVELOPERS: 'Développeurs',
      SIGNUP_P4: 'Informez-vous des nouvelles opportunités et événements dans votre région.',
      SIGNIN_HEADER: 'Ou avec votre compte',
      SIGNIN_EMAIL: 'Nom d\'utilisateur ou courriel',
      SIGNIN_EMAIL_REQUIRED: 'Nom d\'utilisateur ou courriel requis',
      SIGNIN_PASSWORD: 'Mot de passe',
      SIGNIN_PASSWORD_REQUIRED: 'Mot de passe requis',
      SIGNIN_OR: 'ou',
      SIGNIN_FORGOT_PASSWORD: 'Mot de passe oublié?',
      EMAIL: 'Courriel',
      MEMBER_SINCE: 'Membre depuis :',
      OPEN: 'OUVERT',
      CLOSED: 'CLOS',
      EDIT_PROFILE_SUCCESS: '[FR] Edit profile successful',
      EDIT_PROFILE_SUCCESS_TEXT: '[FR] You have requested government user access, the request is now posted for review. You will receive the government access and be able to access gov user functionality as soon as the admin verifies you as government user.',
      EDIT_PROFILE_OPPORTUNITIES: '[FR] We will send you notifications of new Code With Us Opportunities.',
      EDIT_PROFILE_EVENTS: '[FR] We will notify you of upcoming events.',
      EDIT_PROFILE_BLOG: '[FR] We will notify you of new blog posts.',
      EDIT_PROFILE_FAILURE: '[FR] Edit profile failed!',
      404: 'Page non trouvée!',
      403: 'Interdit!',
      400: 'Mauvaise demande',
      IN_PERSON_NO: 'Travail en personne NON requis',
      IN_PERSON_YES: 'Travail en personne requis',
      IN_PERSON_SOME: 'Certains travail en personne requis',
      TEAM_TEAM: 'Équipe',
      TEAM_NEW: 'Nouvelle équipe',
      TEAM_MEMBERS: 'Membres de l\'équipe',
      TEAM_PROJECTS: 'Projets',
      TEAM_OPPORTUNITIES: 'Possibilités liées au l\'equipe',
      PROJECT_NEW: 'Lister un nouveau projet',
      PROJECT_GITHUB_REPO: 'Afficher le dépôt de code sur GitHub',
      PROJECT_MEMBERS: 'Membres du projet',
      PROJECT_OPPORTUNITIES: 'Possibilités liées au projet',
      OPP_NEW: 'Publier une possibilité',
      OPP_CLOSING: 'Date de clôture :',
      OPP_UPDATES: 'Aimeriez-vous <span class="hidden-sm hidden-xs">recevoir </span>des mises à jour<span class="hidden-sm hidden-xs"> sur cette possibilité</span>?',
      OPP_FIXED_PRICE: 'Il s\'agit d\'une possibilité à <strong>prix fixe</strong> régie par les modalités de notre <a href="https://github.com/BCDevExchange/devex/raw/master/Code-with-Us%20Terms_BC%20Developers%20Exchange.pdf">modèle</a> d\'approvisionnement allégé, <i><a href="/codewithus">Programmez avec nous</a></i>.',
      OPP_BACKGROUND: 'Contexte',
      OPP_ACC_CRIT: 'Critères d\'acceptation',
      OPP_PAID: 'Pour être payé le prix fixe pour cette opportunité, vous devez répondre à tous les critères suivants :',
      OPP_PROPOSAL_EVAL: 'Critères d’évaluation de la proposition',
      OPP_SCORED: 'Votre proposition sera notée selon ce critère :',
      OPP_HOW_TO_APPLY: 'Comment présenter une proposition',
      OPP_SUBMIT_BEFORE: 'Soumettez votre proposition avant',
      OPP_INSTRUCTIONS: 'Avec votre proposition, vous devez télécharger une copie des <a href="https://github.com/BCDevExchange/devex/raw/master/Code-with-Us%20Terms_BC%20Developers%20Exchange.pdf">termes Code With Us,</a> pour indiquer votre acceptation des termes.',
      OPP_PLAN: 'Nous prévoyons d\'attribuer cette opportunité par',
      OPP_PLAN2: 'avec le travail pour commencer',
      OPP_GITHUB_LINK: 'Visitez la publication dans GitHub pour voir cette possibilité et publier un commentaire.',
      OPP_POSTED_BY: 'Publié par :',
      OPP_TEAM: 'Équipe :',
      OPP_PROJECT: 'Projet :',
      OPP_CODE: 'Code :',
      OPP_GITHUB_ISSUE: 'Afficher le problème sur GitHub',
      OPP_CREATED_ON: 'Créé le',
      OPP_BY: 'par',
      OPP_UPDATED_ON: 'Mis à jour le',
      PROFILE_SETTINGS: 'Paramètres',
      PROFILE_PRIVACY: 'Confidentialité et notifications',
      FORM_REQUIRED: '(obligatoire)',
      Empty_Department: 'Veuillez faire une sélection',
      Canadian_Air_Transport_Security_Authority: 'Administration canadienne de la sûreté du transport aérien',
      Atlantic_Pilotage_Authority_Canada: 'Administration de pilotage de l\'Atlantique Canada',
      Great_Lakes_Pilotage_Authority_Canada: 'Administration de pilotage des Grands Lacs Canada',
      Laurentian_Pilotage_Authority_Canada: 'Administration de pilotage des Laurentides Canada',
      Pacific_Pilotage_Authority_Canada: 'Administration de pilotage du Pacifique Canada',
      Northern_Pipeline_Agency_Canada: 'Administration du pipe-line du Nord Canada',
      Indigenous_and_Northern_Affairs_Canada: 'Affaires autochtones et du Nord Canada',
      Intergovernmental_Affairs: 'Affaires intergouvernementales',
      Global_Affairs_Canada: 'Affaires mondiales Canada',
      Canadian_Food_Inspection_Agency: 'Agence canadienne d\'inspection des aliments',
      Canadian_Environmental_Assessment_Agency: 'Agence canadienne d\'évaluation environnementale',
      Canadian_Northern_Economic_Development_Agency: 'Agence canadienne de développement économique du Nord',
      Canadian_Pari_Mutuel_Agency: 'Agence canadienne du pari mutuel',
      Financial_Consumer_Agency_of_Canada: 'Agence de la consommation en matière financière du Canada',
      Public_Health_Agency_of_Canada: 'Agence de la santé publique du Canada',
      Canadian_Forces_Housing_Agency: 'Agence de logement des Forces canadiennes',
      Atlantic_Canada_Opportunities_Agency: 'Agence de promotion économique du Canada atlantique',
      Canada_Border_Services_Agency: 'Agence des services frontaliers du Canada',
      Canada_Revenue_Agency: 'Agence du revenu du Canada',
      Federal_Economic_Development_Agency_for_Southern_Ontario: 'Agence fédérale de développement économique pour le Sud de l\'Ontario',
      Canadian_Space_Agency: 'Agence spatiale canadienne',
      Agriculture_and_Agri_Food_Canada: 'Agriculture et Agroalimentaire Canada',
      Veterans_Affairs_Canada: 'Anciens Combattants Canada',
      Canadian_Army: 'Armée canadienne',
      Royal_Canadian_Air_Force: 'Aviation royale canadienne',
      Seniors: 'Aînés',
      Business_Development_Bank_of_Canada: 'Banque de développement du Canada',
      Bank_of_Canada: 'Banque du Canada',
      Library_and_Archives_Canada: 'Bibliothèque et Archives Canada',
      Procurement_Ombudsman: 'Bureau de l\'ombudsman de l\'approvisionnement',
      Taxpayers_Ombudsman: 'Bureau de l\'ombudsman des contribuables',
      Federal_Ombudsman_for_Victims_Of_Crime: 'Bureau de l\'ombudsman fédéral des victimes d\'actes criminels',
      Competition_Bureau_Canada: 'Bureau de la concurrence Canada',
      Transportation_Safety_Board_of_Canada: 'Bureau de la sécurité des transports du Canada',
      Translation_Bureau: 'Bureau de la traduction',
      Privy_Council_Office: 'Bureau du Conseil privé',
      Communications_Security_Establishment_Commissioner: 'Bureau du commissaire du Centre de la sécurité des télécommunications',
      Chief_Electoral_Officer: 'Bureau du directeur général des élections',
      Office_of_the_Parliamentary_Budget_Officer: 'Bureau du directeur parlementaire du budget',
      Secretary_to_the_Governor_General: 'Bureau du secrétaire du gouverneur général',
      Superintendent_of_Bankruptcy_Canada: 'Bureau du surintendant des faillites Canada',
      Superintendent_of_Financial_Institutions_Canada: 'Bureau du surintendant des institutions financières Canada',
      Auditor_General_of_Canada: 'Bureau du vérificateur général du Canada',
      CORCAN: 'CORCAN',
      Ship_Source_Oil_Pollution_Fund: 'Caisse d\'indemnisation des dommages dus à la pollution par les hydrocarbures causée par les navires',
      Canadian_Centre_for_Occupational_Health_and_Safety: 'Centre canadien d\'hygiène et de sécurité au travail',
      Canada_Centre_for_Inland_Waters: 'Centre canadien des eaux intérieures',
      Financial_Transactions_and_Reports_Analysis_Centre_of_Canada: 'Centre d\'analyse des opérations et déclarations financières du Canada',
      Communications_Security_Establishment_Canada: 'Centre de la sécurité des télécommunications Canada',
      International_Development_Research_Centre: 'Centre de recherches pour le développement international',
      Communications_Research_Centre_Canada: 'Centre de recherches sur les communications Canada',
      Canada_Firearms_Centre: 'Centre des armes à feu Canada',
      National_Arts_Centre: 'Centre national des arts',
      Canada_Research_Chairs: 'Chaires de recherche du Canada',
      House_of_Commons: 'Chambre des communes',
      Canadian_Police_College: 'Collège canadien de police',
      Royal_Military_College_Saint_Jean: 'Collège militaire royal de Saint-Jean',
      Royal_Military_College_of_Canada: 'Collège militaire royal du Canada',
      Security_Intelligence_Review_Committee: 'Comité de surveillance des activités de renseignement de sécurité',
      Royal_Canadian_Mounted_Police_External_Review_Committee: 'Comité externe d\'examen de la Gendarmerie royale du Canada',
      Military_Grievances_External_Review_Committee: 'Comité externe d\'examen des griefs militaires',
      Commissioner_of_Lobbying_of_Canada: 'Commissariat au lobbying du Canada',
      Conflict_of_Interest_and_Ethics_Commissioner: 'Commissariat aux conflits d\'intérêts et à l\'éthique',
      Commissioner_of_Official_Languages: 'Commissariat aux langues officielles',
      Information_Commissioner: 'Commissariat à l\'information au Canada',
      Public_Sector_Integrity_Commissioner_of_Canada: 'Commissariat à l\'intégrité du secteur public du Canada',
      Commissioner_for_Federal_Judicial_Affairs_Canada: 'Commissariat à la magistrature fédérale Canada',
      Privacy_Commissioner: 'Commissariat à la protection de la vie privée au Canada',
      Canadian_Cultural_Property_Export_Review_Board: 'Commission canadienne d\'examen des exportations de biens culturels',
      Canadian_Nuclear_Safety_Commission: 'Commission canadienne de sûreté nucléaire',
      Canadian_Human_Rights_Commission: 'Commission canadienne des droits de la personne',
      Canadian_Grain_Commission: 'Commission canadienne des grains',
      Canadian_Dairy_Commission: 'Commission canadienne du lait',
      Canadian_Tourism_Commission: 'Commission canadienne du tourisme',
      Civilian_Review_and_Complaints_Commission_for_the_RCMP: 'Commission civile d\'examen et de traitement des plaintes relatives à la GRC',
      Military_Police_Complaints_Commission_of_Canada: 'Commission d\'examen des plaintes concernant la police militaire du Canada',
      Canada_Employment_Insurance_Commission: 'Commission de l\'assurance-emploi du Canada',
      Immigration_and_Refugee_Board_of_Canada: 'Commission de l\'immigration et du statut de réfugié du Canada',
      National_Capital_Commission: 'Commission de la capitale nationale',
      Public_Service_Commission_of_Canada: 'Commission de la fonction publique du Canada',
      Canada_Agricultural_Review_Tribunal: 'Commission de révision agricole du Canada',
      Geographical_Names_Board_of_Canada: 'Commission de toponymie du Canada',
      Indian_Residential_Schools_Truth_and_Reconciliation_Commission: 'Commission de vérité et de réconciliation relative aux pensionnats indiens',
      National_Battlefields_Commission: 'Commission des champs de bataille nationaux',
      Parole_Board_of_Canada: 'Commission des libérations conditionnelles du Canada',
      Historic_Sites_and_Monuments_Board_of_Canada: 'Commission des lieux et monuments historiques du Canada',
      Public_Service_Labour_Relations_and_Employment_Board: 'Commission des relations de travail et de l\'emploi dans la fonction publique',
      Copyright_Board_Canada: 'Commission du droit d\'auteur Canada',
      Status_of_Women_Canada: 'Condition féminine Canada',
      Canadian_Judicial_Council: 'Conseil canadien de la magistrature',
      Standards_Council_of_Canada: 'Conseil canadien des normes',
      Canada_Industrial_Relations_Board: 'Conseil canadien des relations industrielles',
      Patented_Medicine_Prices_Review_Board_Canada: 'Conseil d\'examen du prix des médicaments brevetés Canada',
      Canadian_Radio_Television_and_Telecommunications_Commission: 'Conseil de la radiodiffusion et des télécommunications canadiennes',
      Natural_Sciences_and_Engineering_Research_Canada: 'Conseil de recherches en sciences et en génie Canada',
      Social_Sciences_and_Humanities_Research_Council_of_Canada: 'Conseil de recherches en sciences humaines du Canada',
      Canada_Council_for_the_Arts: 'Conseil des arts du Canada',
      Farm_Products_Council_of_Canada: 'Conseil des produits agricoles du Canada',
      National_Research_Council_Canada: 'Conseil national de recherches Canada',
      National_Seniors_Council: 'Conseil national des aînés',
      Defence_Construction_Canada: 'Construction de Défense Canada',
      Canadian_Commercial_Corporation: 'Corporation commerciale canadienne',
      Canada_Development_Investment_Corporation: 'Corporation de développement des investissements du Canada',
      Tax_Court_of_Canada: 'Cour canadienne de l\'impôt',
      Federal_Court_of_Appeal: 'Cour d\'appel fédérale',
      Federal_Court_of_Canada: 'Cour fédérale',
      Supreme_Court_of_Canada: 'Cour suprême du Canada',
      Destination_Canada: 'Destination Canada',
      Western_Economic_Diversification_Canada: 'Diversification de l\'économie de l\'Ouest Canada',
      National_Defence: 'Défense nationale',
      Canada_Economic_Development_for_Quebec_Regions: 'Développement économique Canada pour les régions du Québec',
      Employment_and_Social_Development_Canada: 'Emploi et Développement social Canada',
      Correctional_Investigator_Canada: 'Enquêteur correctionnel Canada',
      Aboriginal_Business_Canada: 'Entreprise autochtone Canada',
      Environment_and_Climate_Change_Canada: 'Environnement et Changement climatique Canada',
      Export_Development_Canada: 'Exportation et développement Canada',
      Farm_Credit_Canada: 'Financement agricole Canada',
      Finance_Canada: 'Finances Canada, Ministère des',
      Canadian_Race_Relations_Foundation: 'Fondation canadienne des relations raciales',
      Canadian_Coast_Guard: 'Garde côtière canadienne',
      Canada_Gazette: 'Gazette du Canada',
      Royal_Canadian_Mounted_Police: 'Gendarmerie royale du Canada',
      Governor_General_of_Canada: 'Gouverneur général du Canada',
      Registry_of_the_Specific_Claims_Tribunal_of_Canada: 'Greffe du Tribunal des revendications particulières du Canada',
      Clerk_of_the_Privy_Council: 'Greffier du Conseil privé',
      Geomatics_Canada: 'Géomatique Canada',
      Policy_Horizons_Canada: 'Horizons de politiques Canada',
      Immigration_Refugees_and_Citizenship_Canada: 'Immigration, Réfugiés, et Citoyenneté Canada',
      Infrastructure_Canada: 'Infrastructure Canada',
      Federal_Economic_Development_Initiative_for_Northern_Ontario: 'Initiative fédérale de développement économique pour le Nord de l\'Ontario (FedNor)',
      Innovation_Science_and_Economic_Development_Canada: 'Innovation, Sciences et Développement économique Canada',
      Canadian_Conservation_Institute: 'Institut canadien de conservation',
      Democratic_Institutions: 'Institutions démocratiques',
      Canadian_Institutes_of_Health_Research: 'Instituts de recherche en santé du Canada',
      Public_Sector_Pension_Investment_Board: 'Investissement des régimes de pensions du secteur public',
      Justice_Canada: 'Justice Canada, Ministère de la',
      Leader_of_the_Government_in_the_House_of_Commons: 'Leader du gouvernement à la Chambre des communes',
      Marine_Atlantic: 'Marine Atlantique',
      Royal_Canadian_Navy: 'Marine royale canadienne',
      Measurement_Canada: 'Mesures Canada',
      Royal_Canadian_Mint: 'Monnaie royale canadienne',
      Canadian_Museum_of_History: 'Musée canadien de l\'histoire',
      Canadian_Museum_of_Immigration_at_Pier_21: 'Musée canadien de l\'immigration du Quai 21',
      Canadian_War_Museum: 'Musée canadien de la guerre',
      Canadian_Museum_of_Nature: 'Musée canadien de la nature',
      Canadian_Museum_of_Contemporary_Photography: 'Musée canadien de la photographie contemporaine',
      Canadian_Museum_for_Human_Rights: 'Musée canadien pour les droits de la personne',
      Canada_Agriculture_and_Food_Museum: 'Musée de l\'agriculture et de l\'alimentation du Canada',
      Canada_Aviation_and_Space_Museum: 'Musée de l\'aviation et de l\'espace du Canada',
      Currency_Museum: 'Musée de la Banque du Canada',
      National_Gallery_of_Canada: 'Musée des beaux-arts du Canada',
      Virtual_Museum_of_Canada: 'Musée virtuel du Canada',
      National_Museum_of_Science_and_Technology: 'Musées des sciences et de la technologie du Canada',
      Canada_Pension_Plan_Investment_Board: 'Office d\'investissement du régime de pensions du Canada',
      Freshwater_Fish_Marketing_Corporation: 'Office de commercialisation du poisson d\'eau douce',
      Canadian_Intellectual_Property_Office: 'Office de la propriété intellectuelle du Canada',
      Canadian_General_Standards_Board: 'Office des normes générales du Canada',
      Industrial_Technologies_Office: 'Office des technologies industrielles',
      Canadian_Transportation_Agency: 'Office des transports du Canada',
      National_Energy_Board: 'Office national de l\'énergie',
      National_Film_Board: 'Office national du film',
      National_Defence_and_the_Canadian_Forces_Ombudsperson: 'Ombudsman de la Défense nationale et des Forces canadiennes',
      Veterans_Ombudsman: 'Ombudsman des vétérans',
      Canadian_Cadet_Organizations: 'Organisations de cadets du Canada',
      PPP_Canada: 'PPP Canada',
      Parks_Canada: 'Parcs Canada',
      Parliament_of_Canada: 'Parlement du Canada',
      Passport_Canada: 'Passeport Canada',
      Canadian_Heritage: 'Patrimoine canadien',
      Blue_Water_Bridge_Canada: 'Pont Blue Water Canada',
      Jacques_Cartier_and_Champlain_Bridges_Inc: 'Ponts Jacques-Cartier et Champlain Inc.',
      Canada_Post: 'Postes Canada',
      Prime_Minister_of_Canada: 'Premier ministre du Canada',
      Labour_Program: 'Programme du travail',
      Indian_Oil_and_Gas_Canada: 'Pétrole et gaz des Indiens du Canada',
      Fisheries_and_Oceans_Canada: 'Pêches et Océans Canada',
      Receiver_General_for_Canada: 'Receveur général du Canada',
      Defence_Research_and_Development_Canada: 'Recherche et développement pour la Défense Canada',
      Natural_Resources_Canada: 'Ressources naturelles Canada',
      Ridley_Terminals_Inc: 'Ridley Terminals Inc.',
      Canadian_Heritage_Information_Network: 'Réseau canadien d\'information sur le patrimoine',
      Environmental_Protection_Review_Canada: 'Révision de la protection de l\'environnement Canada',
      Health_Canada: 'Santé Canada',
      Polar_Knowledge_Canada: 'Savoir polaire Canada',
      Canadian_Intergovernmental_Conference_Secretariat: 'Secrétariat des conférences intergouvernementales canadiennes',
      Treasury_Board_of_Canada_Secretariat: 'Secrétariat du Conseil du Trésor du Canada',
      National_Search_and_Rescue_Secretariat: 'Secrétariat national recherche et sauvetage',
      Service_Canada: 'Service Canada',
      Courts_Administration_Service: 'Service administratif des tribunaux judiciaires',
      Administrative_Tribunals_Support_Service_of_Canada: 'Service canadien d\'appui aux tribunaux administratifs',
      Canadian_Security_Intelligence_Service: 'Service canadien du renseignement de sécurité',
      Correctional_Service_Canada: 'Service correctionnel Canada',
      Parliamentary_Protective_Service: 'Service de protection parlementaire',
      Canadian_Trade_Commissioner_Service: 'Service des délégués commerciaux du Canada',
      Public_Prosecution_Service_of_Canada: 'Service des poursuites pénales du Canada',
      Shared_Services_Canada: 'Services partagés Canada',
      Public_Services_and_Procurement_Canada: 'Services publics et Approvisionnement Canada',
      Canada_Mortgage_and_Housing_Corporation: 'Société canadienne d\'hypothèques et de logement',
      Canada_Deposit_Insurance_Corporation: 'Société d\'assurance-dépôts du Canada',
      Canada_Science_and_Technology_Museum_Corporation: 'Société des musées de sciences et technologies du Canada',
      Federal_Bridge_Corporation: 'Société des ponts fédéraux',
      Canada_Lands_Company_Limited: 'Société immobilière du Canada',
      Sport_Canada: 'Sport Canada',
      Statistics_Canada: 'Statistique Canada',
      Public_Safety_Canada: 'Sécurité publique Canada',
      Senate_of_Canada: 'Sénat du Canada',
      Transport_Canada: 'Transports Canada',
      Canadian_International_Trade_Tribunal: 'Tribunal canadien du commerce extérieur',
      Transportation_Appeal_Tribunal_of_Canada: 'Tribunal d\'appel des transports du Canada',
      Competition_Tribunal: 'Tribunal de la concurrence',
      Public_Servants_Disclosure_Protection_Tribunal_Canada: 'Tribunal de la protection des fonctionnaires divulgateurs Canada',
      Social_Security_Tribunal_of_Canada: 'Tribunal de la sécurité sociale du Canada',
      Occupational_Health_and_Safety_Tribunal_Canada: 'Tribunal de santé et sécurité au travail Canada',
      Veterans_Review_and_Appeal_Board_Canada: 'Tribunal des anciens combattants (révision et appel) Canada',
      Human_Rights_Tribunal_of_Canada: 'Tribunal des droits de la personne du Canada',
      Telefilm_Canada: 'Téléfilm Canada',
      VIA_Rail_Canada_Inc: 'VIA Rail Canada Inc.',
      Canada_School_of_Public_Service: 'École de la fonction publique du Canada',
      Elections_Canada: 'Élections Canada',
      Atomic_Energy_of_Canada_Limited: 'Énergie atomique du Canada, Limitée',
      500: '500 $',
      1000: '1 000 $',
      1500: '1 500 $',
      2000: '2 000 $',
      2500: '2 500 $',
      3000: '3 000 $',
      3500: '3 500 $',
      4000: '4 000 $',
      4500: '4 500 $',
      5000: '5 000 $',
      5500: '5 500 $',
      6000: '6 000 $',
      6500: '6 500 $',
      7000: '7 000 $',
      7500: '7 500 $',
      8000: '8 000 $',
      8500: '8 500 $',
      9000: '9 000 $',
      9500: '9 500 $',
      10000: '10 000 $'
    })
    .preferredLanguage('en');
  }


  // Then define the init function for starting up the application
  angular.element(document).ready(init);

  function init() {
    // Fixing facebook bug with redirect
    if ((window.location.hash && window.location.hash === '#_=_') && (window.history && history.pushState)) {
        window.history.pushState('', document.title, window.location.pathname);
    }

    // Then init the app
    angular.bootstrap(document, [app.applicationModuleName]);
  }
}(ApplicationConfiguration));
