(function () {
	'use strict';
	var citylist = [
		'Victoria',
		'Vancouver',
		'100 Mile House',
		'Abbotsford',
		'Armstrong',
		'Barriere',
		'Burnaby',
		'Campbell River',
		'Castlegar',
		'Central Saanich',
		'Chetwynd',
		'Chilliwack',
		'Clearwater',
		'Coldstream',
		'Colwood',
		'Comox',
		'Coquitlam',
		'Courtenay',
		'Cranbrook',
		'Creston',
		'Dawson Creek',
		'Delta',
		'Duncan',
		'Elkford',
		'Enderby',
		'Esquimalt',
		'Fernie',
		'Fort St. James',
		'Fort St. John',
		'Grand Forks',
		'Greenwood',
		'Highlands',
		'Hope',
		'Houston',
		'Hudson\'s Hope',
		'Invermere',
		'Kamloops',
		'Kelowna',
		'Kent',
		'Kimberley',
		'Kitimat',
		'Ladysmith',
		'Lake Country',
		'Langford',
		'Langley',
		'Langley',
		'Lantzville',
		'Lillooet',
		'Logan Lake',
		'Mackenzie',
		'Maple Ridge',
		'Merritt',
		'Metchosin',
		'Mission',
		'Nanaimo',
		'Nelson',
		'New Hazelton',
		'New Westminster',
		'North Cowichan',
		'North Saanich',
		'North Vancouver',
		'North Vancouver',
		'Northern Rockies',
		'Oak Bay',
		'Parksville',
		'Peachland',
		'Penticton',
		'Pitt Meadows',
		'Port Alberni',
		'Port Coquitlam',
		'Port Edward',
		'Port Hardy',
		'Port Moody',
		'Powell River',
		'Prince George',
		'Prince Rupert',
		'Qualicum Beach',
		'Quesnel',
		'Revelstoke',
		'Richmond',
		'Rossland',
		'Saanich',
		'Salmon Arm',
		'Sechelt',
		'Sicamous',
		'Sidney',
		'Smithers',
		'Sooke',
		'Spallumcheen',
		'Sparwood',
		'Squamish',
		'Stewart',
		'Summerland',
		'Surrey',
		'Taylor',
		'Terrace',
		'Tofino',
		'Trail',
		'Tumbler Ridge',
		'Ucluelet',
		'Vanderhoof',
		'Vernon',
		'View Royal',
		'Wells',
		'West Kelowna',
		'West Vancouver',
		'White Rock',
		'Williams Lake'
	];
	var capabilities = [
		{id:'agile-coach', text:'Agile Coach'},
		{id:'backend-web-developer', text:'Backend Web Developer'},
		{id:'business-analyst', text:'Business Analyst'},
		{id:'delivery-manager', text:'Delivery Manager'},
		{id:'devops-engineer', text:'DevOps Engineer'},
		{id:'digital-performance-analyst', text:'Digital Performance Analyst'},
		{id:'frontend-web-developer', text:'Frontend Web Developer'},
		{id:'interaction-designer-user-researcher-usability-tester', text:'Interaction Designer / User Researcher / Usability Tester'},
		{id:'product-manager', text:'Product Manager'},
		{id:'security-engineer', text:'Security Engineer'},
		{id:'technical-architect', text:'Technical Architect'},
		{id:'visual-designer', text:'Visual Designer'},
		{id:'writer-content-designer-content-strategist', text:'Writer / Content Designer / Content Strategist'}
	];
	var departments = [
		'Aboriginal_Business_Canada',
		'Administrative_Tribunals_Support_Service_of_Canada',
		'Agriculture_and_Agri_Food_Canada',
		'Atlantic_Canada_Opportunities_Agency',
		'Atlantic_Pilotage_Authority_Canada',
		'Atomic_Energy_of_Canada_Limited',
		'Auditor_General_of_Canada',
		'Bank_of_Canada',
		'Blue_Water_Bridge_Canada',
		'Business_Development_Bank_of_Canada',
		'CORCAN',
		'Canada_Agricultural_Review_Tribunal',
		'Canada_Agriculture_and_Food_Museum',
		'Canada_Aviation_and_Space_Museum',
		'Canada_Border_Services_Agency',
		'Canada_Centre_for_Inland_Waters',
		'Canada_Council_for_the_Arts',
		'Canada_Deposit_Insurance_Corporation',
		'Canada_Development_Investment_Corporation',
		'Canada_Economic_Development_for_Quebec_Regions',
		'Canada_Employment_Insurance_Commission',
		'Canada_Firearms_Centre',
		'Canada_Gazette',
		'Canada_Industrial_Relations_Board',
		'Canada_Lands_Company_Limited',
		'Canada_Mortgage_and_Housing_Corporation',
		'Canada_Pension_Plan_Investment_Board',
		'Canada_Post',
		'Canada_Research_Chairs',
		'Canada_Revenue_Agency',
		'Canada_School_of_Public_Service',
		'Canada_Science_and_Technology_Museum_Corporation',
		'Canadian_Air_Transport_Security_Authority',
		'Canadian_Army',
		'Canadian_Cadet_Organizations',
		'Canadian_Centre_for_Occupational_Health_and_Safety',
		'Canadian_Coast_Guard',
		'Canadian_Commercial_Corporation',
		'Canadian_Conservation_Institute',
		'Canadian_Cultural_Property_Export_Review_Board',
		'Canadian_Dairy_Commission',
		'Canadian_Environmental_Assessment_Agency',
		'Canadian_Food_Inspection_Agency',
		'Canadian_Forces_Housing_Agency',
		'Canadian_General_Standards_Board',
		'Canadian_Grain_Commission',
		'Canadian_Heritage',
		'Canadian_Heritage_Information_Network',
		'Canadian_Human_Rights_Commission',
		'Canadian_Institutes_of_Health_Research',
		'Canadian_Intellectual_Property_Office',
		'Canadian_Intergovernmental_Conference_Secretariat',
		'Canadian_International_Trade_Tribunal',
		'Canadian_Judicial_Council',
		'Canadian_Museum_for_Human_Rights',
		'Canadian_Museum_of_Contemporary_Photography',
		'Canadian_Museum_of_History',
		'Canadian_Museum_of_Immigration_at_Pier_21',
		'Canadian_Museum_of_Nature',
		'Canadian_Northern_Economic_Development_Agency',
		'Canadian_Nuclear_Safety_Commission',
		'Canadian_Pari_Mutuel_Agency',
		'Canadian_Police_College',
		'Canadian_Race_Relations_Foundation',
		'Canadian_Radio_Television_and_Telecommunications_Commission',
		'Canadian_Security_Intelligence_Service',
		'Canadian_Space_Agency',
		'Canadian_Tourism_Commission',
		'Canadian_Trade_Commissioner_Service',
		'Canadian_Transportation_Agency',
		'Canadian_War_Museum',
		'Chief_Electoral_Officer',
		'Civilian_Review_and_Complaints_Commission_for_the_RCMP',
		'Clerk_of_the_Privy_Council',
		'Commissioner_for_Federal_Judicial_Affairs_Canada',
		'Commissioner_of_Lobbying_of_Canada',
		'Commissioner_of_Official_Languages',
		'Communications_Research_Centre_Canada',
		'Communications_Security_Establishment_Canada',
		'Communications_Security_Establishment_Commissioner',
		'Competition_Bureau_Canada',
		'Competition_Tribunal',
		'Conflict_of_Interest_and_Ethics_Commissioner',
		'Copyright_Board_Canada',
		'Correctional_Investigator_Canada',
		'Correctional_Service_Canada',
		'Courts_Administration_Service',
		'Currency_Museum',
		'Defence_Construction_Canada',
		'Defence_Research_and_Development_Canada',
		'Democratic_Institutions',
		'Destination_Canada',
		'Elections_Canada',
		'Employment_and_Social_Development_Canada',
		'Environment_and_Climate_Change_Canada',
		'Environmental_Protection_Review_Canada',
		'Export_Development_Canada',
		'Farm_Credit_Canada',
		'Farm_Products_Council_of_Canada',
		'Federal_Bridge_Corporation',
		'Federal_Court_of_Appeal',
		'Federal_Court_of_Canada',
		'Federal_Economic_Development_Agency_for_Southern_Ontario',
		'Federal_Economic_Development_Initiative_for_Northern_Ontario',
		'Federal_Ombudsman_for_Victims_Of_Crime',
		'Finance_Canada',
		'Financial_Consumer_Agency_of_Canada',
		'Financial_Transactions_and_Reports_Analysis_Centre_of_Canada',
		'Fisheries_and_Oceans_Canada',
		'Freshwater_Fish_Marketing_Corporation',
		'Geographical_Names_Board_of_Canada',
		'Geomatics_Canada',
		'Global_Affairs_Canada',
		'Governor_General_of_Canada',
		'Great_Lakes_Pilotage_Authority_Canada',
		'Health_Canada',
		'Historic_Sites_and_Monuments_Board_of_Canada',
		'House_of_Commons',
		'Human_Rights_Tribunal_of_Canada',
		'Immigration_and_Refugee_Board_of_Canada',
		'Immigration,_Refugees_and_Citizenship_Canada',
		'Indian_Oil_and_Gas_Canada',
		'Indian_Residential_Schools_Truth_and_Reconciliation_Commission',
		'Indigenous_and_Northern_Affairs_Canada',
		'Industrial_Technologies_Office',
		'Information_Commissioner',
		'Infrastructure_Canada',
		'Innovation,_Science_and_Economic_Development_Canada',
		'Intergovernmental_Affairs',
		'International_Development_Research_Centre',
		'Jacques_Cartier_and_Champlain_Bridges_Inc',
		'Justice_Canada',
		'Labour_Program',
		'Laurentian_Pilotage_Authority_Canada',
		'Leader_of_the_Government_in_the_House_of_Commons',
		'Library_and_Archives_Canada',
		'Marine_Atlantic',
		'Measurement_Canada',
		'Military_Grievances_External_Review_Committee',
		'Military_Police_Complaints_Commission_of_Canada',
		'National_Arts_Centre',
		'National_Battlefields_Commission',
		'National_Capital_Commission',
		'National_Defence',
		'National_Defence_and_the_Canadian_Forces_Ombudsperson',
		'National_Energy_Board',
		'National_Film_Board',
		'National_Gallery_of_Canada',
		'National_Museum_of_Science_and_Technology',
		'National_Research_Council_Canada',
		'National_Search_and_Rescue_Secretariat',
		'National_Seniors_Council',
		'Natural_Resources_Canada',
		'Natural_Sciences_and_Engineering_Research_Canada',
		'Northern_Pipeline_Agency_Canada',
		'Occupational_Health_and_Safety_Tribunal_Canada',
		'PPP_Canada',
		'Pacific_Pilotage_Authority_Canada',
		'Parks_Canada',
		'Parliament_of_Canada',
		'Office_of_the_Parliamentary_Budget_Officer',
		'Parliamentary_Protective_Service',
		'Parole_Board_of_Canada',
		'Passport_Canada',
		'Patented_Medicine_Prices_Review_Board_Canada',
		'Polar_Knowledge_Canada',
		'Policy_Horizons_Canada',
		'Prime_Minister_of_Canada',
		'Privacy_Commissioner',
		'Privy_Council_Office',
		'Procurement_Ombudsman',
		'Public_Health_Agency_of_Canada',
		'Public_Prosecution_Service_of_Canada',
		'Public_Safety_Canada',
		'Public_Sector_Integrity_Commissioner_of_Canada',
		'Public_Sector_Pension_Investment_Board',
		'Public_Servants_Disclosure_Protection_Tribunal_Canada',
		'Public_Service_Commission_of_Canada',
		'Public_Service_Labour_Relations_and_Employment_Board',
		'Public_Services_and_Procurement_Canada',
		'Receiver_General_for_Canada',
		'Registry_of_the_Specific_Claims_Tribunal_of_Canada',
		'Ridley_Terminals_Inc',
		'Royal_Canadian_Air_Force',
		'Royal_Canadian_Mint',
		'Royal_Canadian_Mounted_Police',
		'Royal_Canadian_Mounted_Police_External_Review_Committee',
		'Royal_Canadian_Navy',
		'Royal_Military_College_Saint_Jean',
		'Royal_Military_College_of_Canada',
		'Secretary_to_the_Governor_General',
		'Security_Intelligence_Review_Committee',
		'Senate_of_Canada',
		'Seniors',
		'Service_Canada',
		'Shared_Services_Canada',
		'Ship_Source_Oil_Pollution_Fund',
		'Social_Sciences_and_Humanities_Research_Council_of_Canada',
		'Social_Security_Tribunal_of_Canada',
		'Sport_Canada',
		'Standards_Council_of_Canada',
		'Statistics_Canada',
		'Status_of_Women_Canada',
		'Superintendent_of_Bankruptcy_Canada',
		'Superintendent_of_Financial_Institutions_Canada',
		'Supreme_Court_of_Canada',
		'Tax_Court_of_Canada',
		'Taxpayers_Ombudsman',
		'Telefilm_Canada',
		'Translation_Bureau',
		'Transport_Canada',
		'Transportation_Appeal_Tribunal_of_Canada',
		'Transportation_Safety_Board_of_Canada',
		'Treasury_Board_of_Canada_Secretariat',
		'VIA_Rail_Canada_Inc',
		'Veterans_Affairs_Canada',
		'Veterans_Review_and_Appeal_Board_Canada',
		'Veterans_Ombudsman',
		'Virtual_Museum_of_Canada',
		'Western_Economic_Diversification_Canada'
	];
	var prices = [
		'500',
		'1000',
		'1500',
		'2000',
		'2500',
		'3000',
		'3500',
		'4000',
		'4500',
		'5000',
		'5500',
		'6000',
		'6500',
		'7000',
		'7500',
		'8000',
		'8500',
		'9000',
		'9500',
		'9999'
	];

	angular.module('core')

	.factory ('dataService', function () {
		return {
			cities: citylist,
			capabilities : capabilities,
			departments : departments,
			prices : prices
		};
	});
}());

